<?php

/**
 * @file
 * Main module file for termfilter. Replaces terms inside posts with filtered versions.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @param $section
 *   string file path
 *
 * @return
 *   string
 */
function termfilter_help($page = 'admin/help#termfilter', RouteMatchInterface $routeMatch) {
  switch ($page) {
    case 'admin/modules#description':
      return t('<p>Replaces whitelisted terms inside posts with &lt;a&gt; tags.</p>');
    case 'admin/help#termfilter':
      return t('<p>The Termfilter module allows you to filter terms in site content and replace the filtered terms with a tags linking to the taxonomy term view page.');
    case 'termfilter.admin':
      //return t('<p>In order for filtering to work on the body text of a node or comment, you must activate the Termfilter filter for the input formats you wish to enable filtering for. Check your filter settings at <a href="@filter">Input Formats</a>.</p>', array('@filter' => url('admin/config/content/filters')));
  }
}
