<?php

/**
 * @file
 * Main module file for termfilter. Replaces terms inside posts with filtered versions.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function termfilter_help($page, RouteMatchInterface $routeMatch) {
  switch ($page) {
    case 'help.page.termfilter':
      return t('<p>In order for filtering to work on the body text of a node or comment, you must activate the Termfilter filter for the input formats you wish to enable filtering for. Check your filter settings at <a href="@filter">Input Formats</a>.</p>', 
        array('@filter' => Url::fromRoute('termfilter.admin')->toString()));
  }
}
